### ISSUE TITLE
webpack v5 do not need to install terser-webpack-plugin

### ISSUE THREAD

**Issue by nardoyala** [taniarascia/webpack-boilerplate#19]
I was checking your configuration files in order to build a webpack boilerplate by myself and I noticed that inside the config file named `webpack.prod.js` you are using a plugin called `terser-webpack-plugin`.

I wanted to learn what is that plugin used for, so I went to the [documentation](https://webpack.js.org/plugins/terser-webpack-plugin/) and I found this piece of information: 

> If you are using webpack v5 or above you do not need to install this plugin. Webpack v5 comes with the latest terser-webpack-plugin out of the box.

I'm not an experienced developer, so I'm not sure if you really need to install that plugin in your project boilerplate, but I think is worth checking it out.

**Comment by taniarascia** [comment]
Good plan, feel free to open a PR to remove it or I'll get to it.

**Comment by nardoyala** [comment]
Fantastic! I'd love to make a PR to this repo. I'll do it right now after I read a little bit more documentation so I won't break anything.

**Comment by nardoyala** [comment]
I've already sent a PR fixing this. Thanks for letting me doing it by myself.

**Comment by taniarascia** [comment]
Thanks, @nardoyala. The proper flow is to leave this issue open, and in your PR write `Closes #19` and when the PR is merged the issue will close.

**Comment by nardoyala** [comment]
Thank you for explaining me the proper flow, this is a complete new world for me 😅. I'll add `Closes #19` in my PR then.
