### ISSUE TITLE
is importing the only way to use images ?

### ISSUE THREAD

**Issue by one618** [taniarascia/webpack-boilerplate#22]
excuses my beginner question, 

If I added any image to my html `<img src="./images/example.jpg" alt="">` I'm always getting a 404 error
do I have to import all the images I want to use in js ?

**Comment by tpkahlon** [comment]
If you are using boilerplate in terms of SPA approach, you can get images in your component using `import` tag like following:

```js
import profilePicture from '../public/example.jpg'
const profilePictureEl = document.createElement('img')
profilePictureEl.setAttribute('src', profilePicture)
app.append(logo, profilePictureEl)
```

If you are using boilerplate as a static application, you can get images in your HTML files using `require`. You can read it more [here](https://stackoverflow.com/a/47127094).

```html
<body>
    <img src="<%= require('../public/example.jpg') %>">
    <div id="root"></div>
</body>
```

**Comment by one618** [comment]
@tpkahlon thank you so much for your time and efforts it works now

**Comment by alex-drocks** [comment]
Hello I'm less than 1 year experimented with javascript and I wonder how to use a SPA model if ou want like 4 pages in a website? I've been using htmlwebpackplugin to generate multiple pages but is this even a good approach? Problem is that with this approach I need to work in the html of pages templates. Any idea for improvement ?
