### ISSUE TITLE
npm run build doesn't copy fonts

### ISSUE THREAD

**Issue by one618** [taniarascia/webpack-boilerplate#23]
I tested on the main code without changing anything the inter font is not being copied to dist folder after building
also the 2 js files are not minified, sorry for too many questions.

**Comment by taniarascia** [comment]
The font data is located in the CSS files. @nardoyala did removing TerserWebpackPlugin stop the code from being minified?

**Comment by nardoyala** [comment]
@taniarascia oh! I forgot to extend the default webpack 5 minimizer inside the configuration file, right now it looks like this:

`minimizer: [new OptimizeCssAssetsPlugin()],`

But it should be like this:

`minimizer: [new OptimizeCssAssetsPlugin(), "..."],`

That way the Terser Plugin included in WebPack 5 doesn't get overwritten. I'm so sorry, I'll fix it right away.

**Comment by taniarascia** [comment]
No problem at all, thanks for the quick follow up!

**Comment by one618** [comment]
works fine now thanks guyz
