### ISSUE TITLE
Implementation of Prettier and ESLint

### ISSUE THREAD

**Issue by tpkahlon** [taniarascia/webpack-boilerplate#25]
**Issue**

- Setup lint configuration (prettier and eslint) for developers to adhere to best practices following popular style guide (default is set to `airbnb-base`)
- Availability of `npm run lint` command to quickly go through warnings/cautions before pushing a feature to production after a staging review is approved

**Pitch**

- Do you feel this improvement can be helpful for audience?

**Possible Solution**

- If above pitch sounds reasonable, see recent [commits](https://github.com/tpkahlon/webpack-boilerplate/commits/master), clone this [repo](https://github.com/tpkahlon/webpack-boilerplate) for a quick test and let me know if you would like to see a PR for this
- In case if these add-ons bring extra overhead code and complicate things, feel free to close this issue

**Comment by one618** [comment]
it's amazing actually i was looking for something like that, it would be amazing also if you also can guide us to do something like the following :

i want to use webp images with the picture tag to use both jpg and webp, is it possible to add a plugin to automatically convert jpg to webp and optimize all images when building ? it's so much pain to do that manually for each image

**Comment by tpkahlon** [comment]
@one618 Currently, lint method works in two ways. One is automated where it assumes developer has eslint, prettier plugins installed in their code editor. It picks up setting values from configuration files and immediately throw squiggly lines to highlight areas in code that can be improved. Second way is manual where developer do not want to be reminded of lint options. They continue writing their code and once they have a working prototype of something, they can run `npm run lint` to polish syntax before moving code to production.

It is possible to have lint logs when development server is run. I am not sure if it will be an intuitive process for developer that way. Webpack logs so many things that are processes related. Adding lint logs in between may overwhelm author. However, I will look into it more. Maybe, there are better ways to print logs in development environment.

**Comment by tpkahlon** [comment]
@one618 Following up to your suggestion:
- I have implemented ESLint in Webpack that kicks in when author runs development environment via `npm run start`. Errors/Cautions are logged in the terminal and further execution in HMR pauses until issues are cleared. Once everything passes through lint process, HMR kicks back in and changes within SCSS/JS/HTML files automatically reload the application. You can clone this [version](https://github.com/tpkahlon/webpack-boilerplate) for testing purposes.
- As a backup, author can always run `npm run lint` command if they are not running development environment.

**Comment by one618** [comment]
@tpkahlon thank you for your efforts i cloned the repo but it doesn't seem to be showing any errors on the console, is it working for you ?

**Comment by tpkahlon** [comment]
@one618 Yes, it should show errors. See this [screen-cast](https://imgur.com/6rX1COu) for reference.

**Comment by tpkahlon** [comment]
Hey guys, I am following up to see if you got a chance to look into [prettier-eslint](https://github.com/tpkahlon/webpack-boilerplate) implementation. I'd be great to know if you want me to maintain a fork of original repository on weekly basis so it is up-to-date with main branch or would like to see a PR to incorporate these changes in main branch.

**Comment by hyber-code** [comment]
> Hey guys, I am following up to see if you got a chance to look into [prettier-eslint](https://github.com/tpkahlon/webpack-boilerplate) implementation. I'd be great to know if you want me to maintain forked repository on weekly basis so it is up-to-date with main branch or would like to see a PR to incorporate these changes in main branch.
> 
> Ideally, I would prefer to actively maintain forked version with new changes. That way, authors have liberty to choose either option. If @taniarascia agree with this, this ticket can be closed.

hi @tpkahlon I used your fork and its perfect, atleast for my use case. specially the lint part , hot reload. thank you.

**Comment by taniarascia** [comment]
Hi @tpkahlon, sorry for the delay on this. You would prefer to keep and maintain a forked version? I didn't want to introduce any additional complexity and confusion, but prettier and ESLint is a common use-case that I'm sure a lot of people would appreciate. I think it might make more sense to integrate it into this codebase and I can give you maintainer access of the codebase. Does that work?

**Comment by tpkahlon** [comment]
Great, that works for me.

I have already prepared a [V2.1.0](https://github.com/tpkahlon/webpack-boilerplate/tree/Version-2.1.0). Once I have maintainer access, I can send a PR to you for review.
