### ISSUE TITLE
Should be package.lock.json be added to .gitignore?

### ISSUE THREAD

**Issue by brauliodiez** [taniarascia/webpack-boilerplate#28]
I have mixed feelings with this issue, on the one hand it can be good to keep a package.lock json to ensure all is well referenced, on the other this is a boiler plate and it can be a pain in the neck to go back and forth with the package.lock.json on each pull request where a new package is added (maybe I'm missing something, sorry about that).

**Comment by tpkahlon** [comment]
My suggestion is to create a duplicate copy of `package-lock.json` whenever you are working on a new feature locally. If you plan to install new dependencies, `package-lock.json` will change. But, you can override content from backup file. That way, `package-lock.json` would never become a part of your commits. Feel free to make recommendation if you can suggest better approach.

**Comment by taniarascia** [comment]
I'm keeping it as it's the common practice, but I have no strong feelings either way.
