### ISSUE TITLE
insert another static page in template.html

### ISSUE THREAD

**Issue by hyber-code** [taniarascia/webpack-boilerplate#33]
using the default repo, i tried to place an anchor in template.html ```<a href="page/about.html">"clicke me</a> ``` when i run ```npm start``` and after clicking the linked page following is what i get ```Cannot GET /page/about.html``` how  can i add linked static pages to the dev and prod build, thank you in advance.

note: i created page folder in src and kept all my refrenced pages.

**Comment by hyber-code** [comment]
tested another webpack 5 boiler plate and turned out that somehow terser was causing the issue.

**Comment by taniarascia** [comment]
If you wanted to add an about page, you would do add another `HtmlWebpackPlugin` entry:

```
    new HtmlWebpackPlugin({
      title: 'webpack Boilerplate',
      favicon: paths.src + '/images/favicon.png',
      template: paths.src + '/template.html', // template file
      filename: 'index.html', // output file
    }),
    new HtmlWebpackPlugin({
      title: 'About',
      template: paths.src + '/about.html',
      filename: 'about.html',
    }),
```

Then you can link in your `index.html` to `about.html`.

**Comment by hyber-code** [comment]
Thank you @taniarascia
