### ISSUE TITLE
HMR only works once after the update failed

### ISSUE THREAD

**Issue by jfroffice** [taniarascia/webpack-boilerplate#42]
and the reload of the page also failed.

![image](https://user-images.githubusercontent.com/964701/103664017-127d4e00-4f72-11eb-902d-bb7c4ca9ae6e.png)

**Comment by tpkahlon** [comment]
@jfroffice: Hello!

Can you please try commenting out line `19` and line `38-41` in `webpack.dev.js`?

Please report if above line clear blockers for you? If so, @taniarascia might need to look at it.

**Comment by waldronmatt** [comment]
@jfroffice if you are using multiple entrypoints with HMR, set optimization.runtimeChunk: "single". https://github.com/webpack/webpack-dev-server/issues/2792

**Comment by jfroffice** [comment]
@waldronmatt thx for the recommandation, I will have a try.

**Comment by jfroffice** [comment]
@tpkahlon sounds to have the same behavior, it only works once.

> @jfroffice: Hello!
> 
> Can you please try commenting out line `19` and line `38-41` in `webpack.dev.js`?
> 
> Please report if above line clear blockers for you? If so, @taniarascia might need to look at it.

**Comment by jfroffice** [comment]
@waldronmatt  some chunks are getting bigger than the previous Webpack configuration, probably a `downside` from this configuration. But the build is going faster.

**Comment by taniarascia** [comment]
Hello. I tested out several changes to both the Sass files and JavaScript files in the dev environment, and did not encounter any issue. If this issue is ongoing, let me know, otherwise I'll close it.

**Comment by jfroffice** [comment]
Can be close actually.
