### ISSUE TITLE
Adding Style Classes and IDs not working

### ISSUE THREAD

**Issue by gabedeko** [taniarascia/webpack-boilerplate#46]
Hello,

When I add styles to classes and IDs in my SCSS files they don't render but if I add styles to tags(h1, dic, etc.) they do render.

[Screenshot](
https://drive.google.com/file/d/1Azn7F0bh6cgqo9m0Jc7zzaNLYe_KrB6_/view?usp=sharing)

Has anyone else experienced something similar to this?

**Comment by ivantacca** [comment]
I have the same problem

**Comment by gofka** [comment]
Hi. I've faced the same issue. Just set `modules` option to false in css-loader

```
// Styles: Inject CSS into the head with source maps
{
  test: /\.(scss|css)$/,
  use: [
    'style-loader',
    { loader: 'css-loader', options: { sourceMap: true, importLoaders: 1, modules: false } },
    { loader: 'postcss-loader', options: { sourceMap: true } },
    { loader: 'sass-loader', options: { sourceMap: true } },
  ],
},
```

**Comment by gabedeko** [comment]
Awesome thank you @gofka !
