### ISSUE TITLE
Load fonts from public folder

### ISSUE THREAD

**Issue by eduardfossas** [taniarascia/webpack-boilerplate#47]
Hello, Tania!

First of all, your boilerplate is such an inspiration and a proper way to use webpack 5 that feels unreal.

Now, to the problem. It is possible to declare the @font-face and point to a font folder inside the public folder. I could not manage to do it.

Thanks and ward regards

**Comment by taniarascia** [comment]
Why not just use the fonts in src?

**Comment by eduardfossas** [comment]
Hello, Tania, I discovered the problem. It does not matter where you put them. The problem comes with the CssMiniferPlugin that strips the quotes in the CSS when minified

**Comment by taniarascia** [comment]
So it sounds like the issue doesn't reside with this repo, so I'm going to close the issue.
