### ISSUE TITLE
Production build can't find css/js files

### ISSUE THREAD

**Issue by thegoodcode** [taniarascia/webpack-boilerplate#57]
When you run the build command, and serve the html in dist folder, apart from the contents in the html file alone, it can't find any other resource either it be js files or css files; here you can see a screenshot of the console after page load:

![production error](https://user-images.githubusercontent.com/66324952/136367712-75ec646a-8088-46d6-9f1c-7edb9633a5ee.JPG)

**Comment by taniarascia** [comment]
Can you provide more information? Dev server and prod are working for me. The suggested fix in your PR would break it for me. Is this a Windows issue?

**Comment by digitall-it** [comment]
What version of node are you using? v14.18.0?

**Comment by thegoodcode** [comment]
> What version of node are you using? v14.18.0?v16.11.0?

v14.18.0

**Comment by digitall-it** [comment]
proposed #58 doesn't break dist for me. I am on a Mac.

**Comment by thegoodcode** [comment]
> @taniarascia proposed #58 doesn't break dist for me. I am on a Mac. @thegoodcode it may sound strange, but try switching to v16. I suggest using nvm.

I'm using a new device compared to the time of issue and it may sound stranger that I cannot recreate the issue now. I did not change the npm version and reinstalled the packages with both npm & yarn separately and both worked in development and in production with no issues confirmed.
