### ISSUE TITLE
Cannot apply update. Need to do a full reload!

### ISSUE THREAD

**Issue by tapiamcclung** [taniarascia/webpack-boilerplate#72]
Hi, thanks for the great [tutorial](https://www.taniarascia.com/how-to-use-webpack/). I was following it and also cloned this repo. In both cases, I get 
``` 
Cannot apply update. Need to do a full reload!
[HMR] Aborted because ./src/index.js is not accepted
``` 
whenever I make some changes to `src/index.js`. Changes to a `/src/style.css` file are properly reflected and reloaded.
When running `npm i`, I get a `found 12 vulnerabilities (2 low, 4 moderate, 4 high, 2 critical)` that can be fixed with `npm audit fix`, but doesn't change things related to HMR.

I am using nodejs version 14.16.1 and npm version 6.14.12. Any pointers? Thanks a lot!

Full console output is below.
```
[HMR] Cannot apply update. Need to do a full reload! [log.js:26:11](webpack://webpack-boilerplate/node_modules/webpack/hot/log.js)
[HMR] Aborted because ./src/index.js is not accepted
Update propagation: ./src/index.js
applyHandler@http://localhost:8080/main.bundle.js:10649:31
internalApply/results<@http://localhost:8080/main.bundle.js:10364:21
internalApply@http://localhost:8080/main.bundle.js:10363:54
hotCheck/</</</<@http://localhost:8080/main.bundle.js:10337:26
waitForBlockingPromises@http://localhost:8080/main.bundle.js:10290:55
hotCheck/</</<@http://localhost:8080/main.bundle.js:10335:24
promise callback*hotCheck/</<@http://localhost:8080/main.bundle.js:10334:18
promise callback*hotCheck/<@http://localhost:8080/main.bundle.js:10313:43
promise callback*hotCheck@http://localhost:8080/main.bundle.js:10304:15
check@http://localhost:8080/main.bundle.js:9168:16
./node_modules/webpack/hot/dev-server.js/<@http://localhost:8080/main.bundle.js:9205:7
emit@http://localhost:8080/main.bundle.js:547:17
reloadApp@http://localhost:8080/main.bundle.js:9090:67
ok@http://localhost:8080/main.bundle.js:7276:68
./node_modules/webpack-dev-server/client/socket.js/initSocket/<@http://localhost:8080/main.bundle.js:8822:29
./node_modules/webpack-dev-server/client/clients/WebSocketClient.js/onMessage/this.client.onmessage@http://localhost:8080/main.bundle.js:7128:10
```

**Comment by taniarascia** [comment]
Hi @tapiamcclung. I just tried out a new install and had no issues updating index.js. I believe I would need more information about your setup to be able to debug this, because In don't know what the issue is.

**Comment by tapiamcclung** [comment]
Hi @taniarascia, thanks. The refresh works, but as stated, does a full reload. I only noticed that when inspecting the JS console on the browser.
Will try in a different computer. What else would you need about my setup to debug?
Thanks! :)

**Comment by tapiamcclung** [comment]
Ok, so I tried using a Mac with the same node and npm versions as before and updating index.js works. Maybe the full reload has something to do with using a Windows machine.
