### ISSUE TITLE
非常纯净的一款框架，项目可以根据这个基础框架进行调整，节约不少时间

### ISSUE THREAD

**Issue by ike-yu-byte** [taniarascia/webpack-boilerplate#74]
非常纯净的一款框架，项目可以根据这个基础框架进行调整，节约不少时间

**Comment by ooxi** [comment]
> A very pure framework, the project can be adjusted according to this basic framework, saving a lot of time

Could you please clarify the issue, or was this general feedback?

**Comment by icy0307** [comment]
@ooxi  He just expresses how much he likes your boilerplate, this issue can be closed.
